// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolModel;

#nullable disable

namespace SchoolModel.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20251129002945_aws-initial-1")]
    partial class awsinitial1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolModel.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("county");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("District");
                });

            modelBuilder.Entity("SchoolModel.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int")
                        .HasColumnName("district_id");

                    b.Property<int>("MathScore")
                        .HasColumnType("int")
                        .HasColumnName("math_score");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("NumTestTakers")
                        .HasColumnType("int")
                        .HasColumnName("num_test_takers");

                    b.Property<int>("ReadingScore")
                        .HasColumnType("int")
                        .HasColumnName("reading_score");

                    b.Property<int>("WritingScore")
                        .HasColumnType("int")
                        .HasColumnName("writing_score");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("School");
                });

            modelBuilder.Entity("SchoolModel.School", b =>
                {
                    b.HasOne("SchoolModel.District", "District")
                        .WithMany("Schools")
                        .HasForeignKey("DistrictId")
                        .IsRequired()
                        .HasConstraintName("FK_School_District");

                    b.Navigation("District");
                });

            modelBuilder.Entity("SchoolModel.District", b =>
                {
                    b.Navigation("Schools");
                });
#pragma warning restore 612, 618
        }
    }
}
